/**
 * Nex Event API
 * Utilize essa documentação para realizar a integração com o nosso sistema
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateSponsorUserDto model module.
 * @module model/CreateSponsorUserDto
 * @version 1.0
 */
class CreateSponsorUserDto {
    /**
     * Constructs a new <code>CreateSponsorUserDto</code>.
     * @alias module:model/CreateSponsorUserDto
     * @param publicKey {String} 
     * @param secretKey {String} 
     */
    constructor(publicKey, secretKey) { 
        
        CreateSponsorUserDto.initialize(this, publicKey, secretKey);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, publicKey, secretKey) { 
        obj['publicKey'] = publicKey;
        obj['secretKey'] = secretKey;
    }

    /**
     * Constructs a <code>CreateSponsorUserDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateSponsorUserDto} obj Optional instance to populate.
     * @return {module:model/CreateSponsorUserDto} The populated <code>CreateSponsorUserDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateSponsorUserDto();

            if (data.hasOwnProperty('publicKey')) {
                obj['publicKey'] = ApiClient.convertToType(data['publicKey'], 'String');
            }
            if (data.hasOwnProperty('secretKey')) {
                obj['secretKey'] = ApiClient.convertToType(data['secretKey'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateSponsorUserDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateSponsorUserDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateSponsorUserDto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['publicKey'] && !(typeof data['publicKey'] === 'string' || data['publicKey'] instanceof String)) {
            throw new Error("Expected the field `publicKey` to be a primitive type in the JSON string but got " + data['publicKey']);
        }
        // ensure the json data is a string
        if (data['secretKey'] && !(typeof data['secretKey'] === 'string' || data['secretKey'] instanceof String)) {
            throw new Error("Expected the field `secretKey` to be a primitive type in the JSON string but got " + data['secretKey']);
        }

        return true;
    }


}

CreateSponsorUserDto.RequiredProperties = ["publicKey", "secretKey"];

/**
 * @member {String} publicKey
 */
CreateSponsorUserDto.prototype['publicKey'] = undefined;

/**
 * @member {String} secretKey
 */
CreateSponsorUserDto.prototype['secretKey'] = undefined;






export default CreateSponsorUserDto;

