/**
 * Nex Event API
 * Utilize essa documentação para realizar a integração com o nosso sistema
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CreateParticipantQuizDtoResponsesInner from './CreateParticipantQuizDtoResponsesInner';

/**
 * The CreateParticipantQuizDto model module.
 * @module model/CreateParticipantQuizDto
 * @version 1.0
 */
class CreateParticipantQuizDto {
    /**
     * Constructs a new <code>CreateParticipantQuizDto</code>.
     * @alias module:model/CreateParticipantQuizDto
     * @param isAnonimous {Boolean} 
     * @param responses {Array.<module:model/CreateParticipantQuizDtoResponsesInner>} 
     */
    constructor(isAnonimous, responses) { 
        
        CreateParticipantQuizDto.initialize(this, isAnonimous, responses);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, isAnonimous, responses) { 
        obj['isAnonimous'] = isAnonimous;
        obj['responses'] = responses;
    }

    /**
     * Constructs a <code>CreateParticipantQuizDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateParticipantQuizDto} obj Optional instance to populate.
     * @return {module:model/CreateParticipantQuizDto} The populated <code>CreateParticipantQuizDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateParticipantQuizDto();

            if (data.hasOwnProperty('isAnonimous')) {
                obj['isAnonimous'] = ApiClient.convertToType(data['isAnonimous'], 'Boolean');
            }
            if (data.hasOwnProperty('responses')) {
                obj['responses'] = ApiClient.convertToType(data['responses'], [CreateParticipantQuizDtoResponsesInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateParticipantQuizDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateParticipantQuizDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateParticipantQuizDto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['responses']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['responses'])) {
                throw new Error("Expected the field `responses` to be an array in the JSON data but got " + data['responses']);
            }
            // validate the optional field `responses` (array)
            for (const item of data['responses']) {
                CreateParticipantQuizDtoResponsesInner.validateJSON(item);
            };
        }

        return true;
    }


}

CreateParticipantQuizDto.RequiredProperties = ["isAnonimous", "responses"];

/**
 * @member {Boolean} isAnonimous
 */
CreateParticipantQuizDto.prototype['isAnonimous'] = undefined;

/**
 * @member {Array.<module:model/CreateParticipantQuizDtoResponsesInner>} responses
 */
CreateParticipantQuizDto.prototype['responses'] = undefined;






export default CreateParticipantQuizDto;

