/**
 * Nex Event API
 * Utilize essa documentação para realizar a integração com o nosso sistema
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EventCreateDtoEventTicketsInnerEventTicketDaysInner model module.
 * @module model/EventCreateDtoEventTicketsInnerEventTicketDaysInner
 * @version 1.0
 */
class EventCreateDtoEventTicketsInnerEventTicketDaysInner {
    /**
     * Constructs a new <code>EventCreateDtoEventTicketsInnerEventTicketDaysInner</code>.
     * @alias module:model/EventCreateDtoEventTicketsInnerEventTicketDaysInner
     * @param date {String} 
     */
    constructor(date) { 
        
        EventCreateDtoEventTicketsInnerEventTicketDaysInner.initialize(this, date);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, date) { 
        obj['date'] = date;
    }

    /**
     * Constructs a <code>EventCreateDtoEventTicketsInnerEventTicketDaysInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EventCreateDtoEventTicketsInnerEventTicketDaysInner} obj Optional instance to populate.
     * @return {module:model/EventCreateDtoEventTicketsInnerEventTicketDaysInner} The populated <code>EventCreateDtoEventTicketsInnerEventTicketDaysInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EventCreateDtoEventTicketsInnerEventTicketDaysInner();

            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EventCreateDtoEventTicketsInnerEventTicketDaysInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EventCreateDtoEventTicketsInnerEventTicketDaysInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EventCreateDtoEventTicketsInnerEventTicketDaysInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['date'] && !(typeof data['date'] === 'string' || data['date'] instanceof String)) {
            throw new Error("Expected the field `date` to be a primitive type in the JSON string but got " + data['date']);
        }

        return true;
    }


}

EventCreateDtoEventTicketsInnerEventTicketDaysInner.RequiredProperties = ["date"];

/**
 * @member {String} date
 */
EventCreateDtoEventTicketsInnerEventTicketDaysInner.prototype['date'] = undefined;






export default EventCreateDtoEventTicketsInnerEventTicketDaysInner;

