/**
 * Nex Event API
 * Utilize essa documentação para realizar a integração com o nosso sistema
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EventTicketCouponDashboardDto model module.
 * @module model/EventTicketCouponDashboardDto
 * @version 1.0
 */
class EventTicketCouponDashboardDto {
    /**
     * Constructs a new <code>EventTicketCouponDashboardDto</code>.
     * @alias module:model/EventTicketCouponDashboardDto
     * @param cuponsCreated {Number} 
     * @param cuponsActives {Number} 
     * @param cuponsExpired {Number} 
     */
    constructor(cuponsCreated, cuponsActives, cuponsExpired) { 
        
        EventTicketCouponDashboardDto.initialize(this, cuponsCreated, cuponsActives, cuponsExpired);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, cuponsCreated, cuponsActives, cuponsExpired) { 
        obj['cuponsCreated'] = cuponsCreated;
        obj['cuponsActives'] = cuponsActives;
        obj['cuponsExpired'] = cuponsExpired;
    }

    /**
     * Constructs a <code>EventTicketCouponDashboardDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EventTicketCouponDashboardDto} obj Optional instance to populate.
     * @return {module:model/EventTicketCouponDashboardDto} The populated <code>EventTicketCouponDashboardDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EventTicketCouponDashboardDto();

            if (data.hasOwnProperty('cuponsCreated')) {
                obj['cuponsCreated'] = ApiClient.convertToType(data['cuponsCreated'], 'Number');
            }
            if (data.hasOwnProperty('cuponsActives')) {
                obj['cuponsActives'] = ApiClient.convertToType(data['cuponsActives'], 'Number');
            }
            if (data.hasOwnProperty('cuponsExpired')) {
                obj['cuponsExpired'] = ApiClient.convertToType(data['cuponsExpired'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EventTicketCouponDashboardDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EventTicketCouponDashboardDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EventTicketCouponDashboardDto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

EventTicketCouponDashboardDto.RequiredProperties = ["cuponsCreated", "cuponsActives", "cuponsExpired"];

/**
 * @member {Number} cuponsCreated
 */
EventTicketCouponDashboardDto.prototype['cuponsCreated'] = undefined;

/**
 * @member {Number} cuponsActives
 */
EventTicketCouponDashboardDto.prototype['cuponsActives'] = undefined;

/**
 * @member {Number} cuponsExpired
 */
EventTicketCouponDashboardDto.prototype['cuponsExpired'] = undefined;






export default EventTicketCouponDashboardDto;

