/**
 * Nex Event API
 * Utilize essa documentação para realizar a integração com o nosso sistema
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EventParticipantResponseDtoQuestionsResponsesInnerEventQuizQuestionOptionInner model module.
 * @module model/EventParticipantResponseDtoQuestionsResponsesInnerEventQuizQuestionOptionInner
 * @version 1.0
 */
class EventParticipantResponseDtoQuestionsResponsesInnerEventQuizQuestionOptionInner {
    /**
     * Constructs a new <code>EventParticipantResponseDtoQuestionsResponsesInnerEventQuizQuestionOptionInner</code>.
     * @alias module:model/EventParticipantResponseDtoQuestionsResponsesInnerEventQuizQuestionOptionInner
     * @param eventQuizQuestionOptionId {String} 
     * @param optionDescription {String} 
     * @param isOther {Boolean} 
     * @param userResponse {Boolean} 
     */
    constructor(eventQuizQuestionOptionId, optionDescription, isOther, userResponse) { 
        
        EventParticipantResponseDtoQuestionsResponsesInnerEventQuizQuestionOptionInner.initialize(this, eventQuizQuestionOptionId, optionDescription, isOther, userResponse);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, eventQuizQuestionOptionId, optionDescription, isOther, userResponse) { 
        obj['eventQuizQuestionOptionId'] = eventQuizQuestionOptionId;
        obj['optionDescription'] = optionDescription;
        obj['isOther'] = isOther;
        obj['userResponse'] = userResponse;
    }

    /**
     * Constructs a <code>EventParticipantResponseDtoQuestionsResponsesInnerEventQuizQuestionOptionInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EventParticipantResponseDtoQuestionsResponsesInnerEventQuizQuestionOptionInner} obj Optional instance to populate.
     * @return {module:model/EventParticipantResponseDtoQuestionsResponsesInnerEventQuizQuestionOptionInner} The populated <code>EventParticipantResponseDtoQuestionsResponsesInnerEventQuizQuestionOptionInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EventParticipantResponseDtoQuestionsResponsesInnerEventQuizQuestionOptionInner();

            if (data.hasOwnProperty('eventQuizQuestionOptionId')) {
                obj['eventQuizQuestionOptionId'] = ApiClient.convertToType(data['eventQuizQuestionOptionId'], 'String');
            }
            if (data.hasOwnProperty('optionDescription')) {
                obj['optionDescription'] = ApiClient.convertToType(data['optionDescription'], 'String');
            }
            if (data.hasOwnProperty('isOther')) {
                obj['isOther'] = ApiClient.convertToType(data['isOther'], 'Boolean');
            }
            if (data.hasOwnProperty('userResponse')) {
                obj['userResponse'] = ApiClient.convertToType(data['userResponse'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EventParticipantResponseDtoQuestionsResponsesInnerEventQuizQuestionOptionInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EventParticipantResponseDtoQuestionsResponsesInnerEventQuizQuestionOptionInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EventParticipantResponseDtoQuestionsResponsesInnerEventQuizQuestionOptionInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['eventQuizQuestionOptionId'] && !(typeof data['eventQuizQuestionOptionId'] === 'string' || data['eventQuizQuestionOptionId'] instanceof String)) {
            throw new Error("Expected the field `eventQuizQuestionOptionId` to be a primitive type in the JSON string but got " + data['eventQuizQuestionOptionId']);
        }
        // ensure the json data is a string
        if (data['optionDescription'] && !(typeof data['optionDescription'] === 'string' || data['optionDescription'] instanceof String)) {
            throw new Error("Expected the field `optionDescription` to be a primitive type in the JSON string but got " + data['optionDescription']);
        }

        return true;
    }


}

EventParticipantResponseDtoQuestionsResponsesInnerEventQuizQuestionOptionInner.RequiredProperties = ["eventQuizQuestionOptionId", "optionDescription", "isOther", "userResponse"];

/**
 * @member {String} eventQuizQuestionOptionId
 */
EventParticipantResponseDtoQuestionsResponsesInnerEventQuizQuestionOptionInner.prototype['eventQuizQuestionOptionId'] = undefined;

/**
 * @member {String} optionDescription
 */
EventParticipantResponseDtoQuestionsResponsesInnerEventQuizQuestionOptionInner.prototype['optionDescription'] = undefined;

/**
 * @member {Boolean} isOther
 */
EventParticipantResponseDtoQuestionsResponsesInnerEventQuizQuestionOptionInner.prototype['isOther'] = undefined;

/**
 * @member {Boolean} userResponse
 */
EventParticipantResponseDtoQuestionsResponsesInnerEventQuizQuestionOptionInner.prototype['userResponse'] = undefined;






export default EventParticipantResponseDtoQuestionsResponsesInnerEventQuizQuestionOptionInner;

