/**
 * Nex Event API
 * Utilize essa documentação para realizar a integração com o nosso sistema
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EventParticipantCreateDtoNetworksInner from './EventParticipantCreateDtoNetworksInner';

/**
 * The EventParticipantCreateDto model module.
 * @module model/EventParticipantCreateDto
 * @version 1.0
 */
class EventParticipantCreateDto {
    /**
     * Constructs a new <code>EventParticipantCreateDto</code>.
     * @alias module:model/EventParticipantCreateDto
     * @param name {String} Event participant name
     */
    constructor(name) { 
        
        EventParticipantCreateDto.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>EventParticipantCreateDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EventParticipantCreateDto} obj Optional instance to populate.
     * @return {module:model/EventParticipantCreateDto} The populated <code>EventParticipantCreateDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EventParticipantCreateDto();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('document')) {
                obj['document'] = ApiClient.convertToType(data['document'], 'String');
            }
            if (data.hasOwnProperty('phoneCountry')) {
                obj['phoneCountry'] = ApiClient.convertToType(data['phoneCountry'], 'String');
            }
            if (data.hasOwnProperty('phoneNumber')) {
                obj['phoneNumber'] = ApiClient.convertToType(data['phoneNumber'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
            if (data.hasOwnProperty('networks')) {
                obj['networks'] = ApiClient.convertToType(data['networks'], [EventParticipantCreateDtoNetworksInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EventParticipantCreateDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EventParticipantCreateDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EventParticipantCreateDto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['document'] && !(typeof data['document'] === 'string' || data['document'] instanceof String)) {
            throw new Error("Expected the field `document` to be a primitive type in the JSON string but got " + data['document']);
        }
        // ensure the json data is a string
        if (data['phoneCountry'] && !(typeof data['phoneCountry'] === 'string' || data['phoneCountry'] instanceof String)) {
            throw new Error("Expected the field `phoneCountry` to be a primitive type in the JSON string but got " + data['phoneCountry']);
        }
        // ensure the json data is a string
        if (data['phoneNumber'] && !(typeof data['phoneNumber'] === 'string' || data['phoneNumber'] instanceof String)) {
            throw new Error("Expected the field `phoneNumber` to be a primitive type in the JSON string but got " + data['phoneNumber']);
        }
        // ensure the json data is a string
        if (data['state'] && !(typeof data['state'] === 'string' || data['state'] instanceof String)) {
            throw new Error("Expected the field `state` to be a primitive type in the JSON string but got " + data['state']);
        }
        // ensure the json data is a string
        if (data['city'] && !(typeof data['city'] === 'string' || data['city'] instanceof String)) {
            throw new Error("Expected the field `city` to be a primitive type in the JSON string but got " + data['city']);
        }
        // ensure the json data is a string
        if (data['country'] && !(typeof data['country'] === 'string' || data['country'] instanceof String)) {
            throw new Error("Expected the field `country` to be a primitive type in the JSON string but got " + data['country']);
        }
        if (data['networks']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['networks'])) {
                throw new Error("Expected the field `networks` to be an array in the JSON data but got " + data['networks']);
            }
            // validate the optional field `networks` (array)
            for (const item of data['networks']) {
                EventParticipantCreateDtoNetworksInner.validateJSON(item);
            };
        }

        return true;
    }


}

EventParticipantCreateDto.RequiredProperties = ["name"];

/**
 * Event participant name
 * @member {String} name
 */
EventParticipantCreateDto.prototype['name'] = undefined;

/**
 * Event participant document
 * @member {String} document
 */
EventParticipantCreateDto.prototype['document'] = undefined;

/**
 * Event participant phone country
 * @member {String} phoneCountry
 */
EventParticipantCreateDto.prototype['phoneCountry'] = undefined;

/**
 * Event participant phone number
 * @member {String} phoneNumber
 */
EventParticipantCreateDto.prototype['phoneNumber'] = undefined;

/**
 * Event participant state
 * @member {String} state
 */
EventParticipantCreateDto.prototype['state'] = undefined;

/**
 * Event participant state
 * @member {String} city
 */
EventParticipantCreateDto.prototype['city'] = undefined;

/**
 * Event participant country
 * @member {String} country
 */
EventParticipantCreateDto.prototype['country'] = undefined;

/**
 * @member {Array.<module:model/EventParticipantCreateDtoNetworksInner>} networks
 */
EventParticipantCreateDto.prototype['networks'] = undefined;






export default EventParticipantCreateDto;

