/**
 * Nex Event API
 * Utilize essa documentação para realizar a integração com o nosso sistema
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EventDashboardPanelFinancialDtoSellDiaryByTicketInner model module.
 * @module model/EventDashboardPanelFinancialDtoSellDiaryByTicketInner
 * @version 1.0
 */
class EventDashboardPanelFinancialDtoSellDiaryByTicketInner {
    /**
     * Constructs a new <code>EventDashboardPanelFinancialDtoSellDiaryByTicketInner</code>.
     * @alias module:model/EventDashboardPanelFinancialDtoSellDiaryByTicketInner
     * @param ticket {String} 
     * @param total {Number} 
     * @param date {String} 
     */
    constructor(ticket, total, date) { 
        
        EventDashboardPanelFinancialDtoSellDiaryByTicketInner.initialize(this, ticket, total, date);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, ticket, total, date) { 
        obj['ticket'] = ticket;
        obj['total'] = total;
        obj['date'] = date;
    }

    /**
     * Constructs a <code>EventDashboardPanelFinancialDtoSellDiaryByTicketInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EventDashboardPanelFinancialDtoSellDiaryByTicketInner} obj Optional instance to populate.
     * @return {module:model/EventDashboardPanelFinancialDtoSellDiaryByTicketInner} The populated <code>EventDashboardPanelFinancialDtoSellDiaryByTicketInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EventDashboardPanelFinancialDtoSellDiaryByTicketInner();

            if (data.hasOwnProperty('ticket')) {
                obj['ticket'] = ApiClient.convertToType(data['ticket'], 'String');
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EventDashboardPanelFinancialDtoSellDiaryByTicketInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EventDashboardPanelFinancialDtoSellDiaryByTicketInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EventDashboardPanelFinancialDtoSellDiaryByTicketInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['ticket'] && !(typeof data['ticket'] === 'string' || data['ticket'] instanceof String)) {
            throw new Error("Expected the field `ticket` to be a primitive type in the JSON string but got " + data['ticket']);
        }
        // ensure the json data is a string
        if (data['date'] && !(typeof data['date'] === 'string' || data['date'] instanceof String)) {
            throw new Error("Expected the field `date` to be a primitive type in the JSON string but got " + data['date']);
        }

        return true;
    }


}

EventDashboardPanelFinancialDtoSellDiaryByTicketInner.RequiredProperties = ["ticket", "total", "date"];

/**
 * @member {String} ticket
 */
EventDashboardPanelFinancialDtoSellDiaryByTicketInner.prototype['ticket'] = undefined;

/**
 * @member {Number} total
 */
EventDashboardPanelFinancialDtoSellDiaryByTicketInner.prototype['total'] = undefined;

/**
 * @member {String} date
 */
EventDashboardPanelFinancialDtoSellDiaryByTicketInner.prototype['date'] = undefined;






export default EventDashboardPanelFinancialDtoSellDiaryByTicketInner;

