/**
 * Nex Event API
 * Utilize essa documentação para realizar a integração com o nosso sistema
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EventCreateDtoEventTicketsInnerEventTicketBonusesInner model module.
 * @module model/EventCreateDtoEventTicketsInnerEventTicketBonusesInner
 * @version 1.0
 */
class EventCreateDtoEventTicketsInnerEventTicketBonusesInner {
    /**
     * Constructs a new <code>EventCreateDtoEventTicketsInnerEventTicketBonusesInner</code>.
     * @alias module:model/EventCreateDtoEventTicketsInnerEventTicketBonusesInner
     * @param ticketTitle {String} 
     * @param qtd {Number} 
     */
    constructor(ticketTitle, qtd) { 
        
        EventCreateDtoEventTicketsInnerEventTicketBonusesInner.initialize(this, ticketTitle, qtd);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, ticketTitle, qtd) { 
        obj['ticketTitle'] = ticketTitle;
        obj['qtd'] = qtd;
    }

    /**
     * Constructs a <code>EventCreateDtoEventTicketsInnerEventTicketBonusesInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EventCreateDtoEventTicketsInnerEventTicketBonusesInner} obj Optional instance to populate.
     * @return {module:model/EventCreateDtoEventTicketsInnerEventTicketBonusesInner} The populated <code>EventCreateDtoEventTicketsInnerEventTicketBonusesInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EventCreateDtoEventTicketsInnerEventTicketBonusesInner();

            if (data.hasOwnProperty('ticketTitle')) {
                obj['ticketTitle'] = ApiClient.convertToType(data['ticketTitle'], 'String');
            }
            if (data.hasOwnProperty('qtd')) {
                obj['qtd'] = ApiClient.convertToType(data['qtd'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EventCreateDtoEventTicketsInnerEventTicketBonusesInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EventCreateDtoEventTicketsInnerEventTicketBonusesInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EventCreateDtoEventTicketsInnerEventTicketBonusesInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['ticketTitle'] && !(typeof data['ticketTitle'] === 'string' || data['ticketTitle'] instanceof String)) {
            throw new Error("Expected the field `ticketTitle` to be a primitive type in the JSON string but got " + data['ticketTitle']);
        }

        return true;
    }


}

EventCreateDtoEventTicketsInnerEventTicketBonusesInner.RequiredProperties = ["ticketTitle", "qtd"];

/**
 * @member {String} ticketTitle
 */
EventCreateDtoEventTicketsInnerEventTicketBonusesInner.prototype['ticketTitle'] = undefined;

/**
 * @member {Number} qtd
 */
EventCreateDtoEventTicketsInnerEventTicketBonusesInner.prototype['qtd'] = undefined;






export default EventCreateDtoEventTicketsInnerEventTicketBonusesInner;

