/**
 * Nex Event API
 * Utilize essa documentação para realizar a integração com o nosso sistema
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EventQuizDashboarDtoMultipleChoiceInnerOptionsInner model module.
 * @module model/EventQuizDashboarDtoMultipleChoiceInnerOptionsInner
 * @version 1.0
 */
class EventQuizDashboarDtoMultipleChoiceInnerOptionsInner {
    /**
     * Constructs a new <code>EventQuizDashboarDtoMultipleChoiceInnerOptionsInner</code>.
     * @alias module:model/EventQuizDashboarDtoMultipleChoiceInnerOptionsInner
     * @param optionId {String} 
     * @param optionTitle {String} 
     * @param optionReponseTotal {String} 
     */
    constructor(optionId, optionTitle, optionReponseTotal) { 
        
        EventQuizDashboarDtoMultipleChoiceInnerOptionsInner.initialize(this, optionId, optionTitle, optionReponseTotal);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, optionId, optionTitle, optionReponseTotal) { 
        obj['optionId'] = optionId;
        obj['optionTitle'] = optionTitle;
        obj['optionReponseTotal'] = optionReponseTotal;
    }

    /**
     * Constructs a <code>EventQuizDashboarDtoMultipleChoiceInnerOptionsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EventQuizDashboarDtoMultipleChoiceInnerOptionsInner} obj Optional instance to populate.
     * @return {module:model/EventQuizDashboarDtoMultipleChoiceInnerOptionsInner} The populated <code>EventQuizDashboarDtoMultipleChoiceInnerOptionsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EventQuizDashboarDtoMultipleChoiceInnerOptionsInner();

            if (data.hasOwnProperty('optionId')) {
                obj['optionId'] = ApiClient.convertToType(data['optionId'], 'String');
            }
            if (data.hasOwnProperty('optionTitle')) {
                obj['optionTitle'] = ApiClient.convertToType(data['optionTitle'], 'String');
            }
            if (data.hasOwnProperty('optionReponseTotal')) {
                obj['optionReponseTotal'] = ApiClient.convertToType(data['optionReponseTotal'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EventQuizDashboarDtoMultipleChoiceInnerOptionsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EventQuizDashboarDtoMultipleChoiceInnerOptionsInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EventQuizDashboarDtoMultipleChoiceInnerOptionsInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['optionId'] && !(typeof data['optionId'] === 'string' || data['optionId'] instanceof String)) {
            throw new Error("Expected the field `optionId` to be a primitive type in the JSON string but got " + data['optionId']);
        }
        // ensure the json data is a string
        if (data['optionTitle'] && !(typeof data['optionTitle'] === 'string' || data['optionTitle'] instanceof String)) {
            throw new Error("Expected the field `optionTitle` to be a primitive type in the JSON string but got " + data['optionTitle']);
        }
        // ensure the json data is a string
        if (data['optionReponseTotal'] && !(typeof data['optionReponseTotal'] === 'string' || data['optionReponseTotal'] instanceof String)) {
            throw new Error("Expected the field `optionReponseTotal` to be a primitive type in the JSON string but got " + data['optionReponseTotal']);
        }

        return true;
    }


}

EventQuizDashboarDtoMultipleChoiceInnerOptionsInner.RequiredProperties = ["optionId", "optionTitle", "optionReponseTotal"];

/**
 * @member {String} optionId
 */
EventQuizDashboarDtoMultipleChoiceInnerOptionsInner.prototype['optionId'] = undefined;

/**
 * @member {String} optionTitle
 */
EventQuizDashboarDtoMultipleChoiceInnerOptionsInner.prototype['optionTitle'] = undefined;

/**
 * @member {String} optionReponseTotal
 */
EventQuizDashboarDtoMultipleChoiceInnerOptionsInner.prototype['optionReponseTotal'] = undefined;






export default EventQuizDashboarDtoMultipleChoiceInnerOptionsInner;

