/**
 * Nex Event API
 * Utilize essa documentação para realizar a integração com o nosso sistema
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FindOneDashboardParticipantPanelDtoEventAverageLocationInner model module.
 * @module model/FindOneDashboardParticipantPanelDtoEventAverageLocationInner
 * @version 1.0
 */
class FindOneDashboardParticipantPanelDtoEventAverageLocationInner {
    /**
     * Constructs a new <code>FindOneDashboardParticipantPanelDtoEventAverageLocationInner</code>.
     * @alias module:model/FindOneDashboardParticipantPanelDtoEventAverageLocationInner
     * @param region {String} 
     * @param percentage {Number} 
     */
    constructor(region, percentage) { 
        
        FindOneDashboardParticipantPanelDtoEventAverageLocationInner.initialize(this, region, percentage);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, region, percentage) { 
        obj['region'] = region;
        obj['percentage'] = percentage;
    }

    /**
     * Constructs a <code>FindOneDashboardParticipantPanelDtoEventAverageLocationInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FindOneDashboardParticipantPanelDtoEventAverageLocationInner} obj Optional instance to populate.
     * @return {module:model/FindOneDashboardParticipantPanelDtoEventAverageLocationInner} The populated <code>FindOneDashboardParticipantPanelDtoEventAverageLocationInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FindOneDashboardParticipantPanelDtoEventAverageLocationInner();

            if (data.hasOwnProperty('region')) {
                obj['region'] = ApiClient.convertToType(data['region'], 'String');
            }
            if (data.hasOwnProperty('percentage')) {
                obj['percentage'] = ApiClient.convertToType(data['percentage'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FindOneDashboardParticipantPanelDtoEventAverageLocationInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FindOneDashboardParticipantPanelDtoEventAverageLocationInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of FindOneDashboardParticipantPanelDtoEventAverageLocationInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['region'] && !(typeof data['region'] === 'string' || data['region'] instanceof String)) {
            throw new Error("Expected the field `region` to be a primitive type in the JSON string but got " + data['region']);
        }

        return true;
    }


}

FindOneDashboardParticipantPanelDtoEventAverageLocationInner.RequiredProperties = ["region", "percentage"];

/**
 * @member {String} region
 */
FindOneDashboardParticipantPanelDtoEventAverageLocationInner.prototype['region'] = undefined;

/**
 * @member {Number} percentage
 */
FindOneDashboardParticipantPanelDtoEventAverageLocationInner.prototype['percentage'] = undefined;






export default FindOneDashboardParticipantPanelDtoEventAverageLocationInner;

