/**
 * Nex Event API
 * Utilize essa documentação para realizar a integração com o nosso sistema
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FindTicketByLinkResponseDtoTicketDaysInner model module.
 * @module model/FindTicketByLinkResponseDtoTicketDaysInner
 * @version 1.0
 */
class FindTicketByLinkResponseDtoTicketDaysInner {
    /**
     * Constructs a new <code>FindTicketByLinkResponseDtoTicketDaysInner</code>.
     * @alias module:model/FindTicketByLinkResponseDtoTicketDaysInner
     * @param id {Number} 
     * @param date {Object} 
     */
    constructor(id, date) { 
        
        FindTicketByLinkResponseDtoTicketDaysInner.initialize(this, id, date);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, date) { 
        obj['id'] = id;
        obj['date'] = date;
    }

    /**
     * Constructs a <code>FindTicketByLinkResponseDtoTicketDaysInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FindTicketByLinkResponseDtoTicketDaysInner} obj Optional instance to populate.
     * @return {module:model/FindTicketByLinkResponseDtoTicketDaysInner} The populated <code>FindTicketByLinkResponseDtoTicketDaysInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FindTicketByLinkResponseDtoTicketDaysInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FindTicketByLinkResponseDtoTicketDaysInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FindTicketByLinkResponseDtoTicketDaysInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of FindTicketByLinkResponseDtoTicketDaysInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

FindTicketByLinkResponseDtoTicketDaysInner.RequiredProperties = ["id", "date"];

/**
 * @member {Number} id
 */
FindTicketByLinkResponseDtoTicketDaysInner.prototype['id'] = undefined;

/**
 * @member {Object} date
 */
FindTicketByLinkResponseDtoTicketDaysInner.prototype['date'] = undefined;






export default FindTicketByLinkResponseDtoTicketDaysInner;

