/**
 * Nex Event API
 * Utilize essa documentação para realizar a integração com o nosso sistema
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FindEventInfoDto model module.
 * @module model/FindEventInfoDto
 * @version 1.0
 */
class FindEventInfoDto {
    /**
     * Constructs a new <code>FindEventInfoDto</code>.
     * @alias module:model/FindEventInfoDto
     * @param id {String} 
     * @param title {String} 
     * @param startAt {Object} 
     * @param haveDocument {Boolean} 
     */
    constructor(id, title, startAt, haveDocument) { 
        
        FindEventInfoDto.initialize(this, id, title, startAt, haveDocument);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, title, startAt, haveDocument) { 
        obj['id'] = id;
        obj['title'] = title;
        obj['startAt'] = startAt;
        obj['haveDocument'] = haveDocument;
    }

    /**
     * Constructs a <code>FindEventInfoDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FindEventInfoDto} obj Optional instance to populate.
     * @return {module:model/FindEventInfoDto} The populated <code>FindEventInfoDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FindEventInfoDto();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('startAt')) {
                obj['startAt'] = ApiClient.convertToType(data['startAt'], Object);
            }
            if (data.hasOwnProperty('haveDocument')) {
                obj['haveDocument'] = ApiClient.convertToType(data['haveDocument'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FindEventInfoDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FindEventInfoDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of FindEventInfoDto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }

        return true;
    }


}

FindEventInfoDto.RequiredProperties = ["id", "title", "startAt", "haveDocument"];

/**
 * @member {String} id
 */
FindEventInfoDto.prototype['id'] = undefined;

/**
 * @member {String} title
 */
FindEventInfoDto.prototype['title'] = undefined;

/**
 * @member {Object} startAt
 */
FindEventInfoDto.prototype['startAt'] = undefined;

/**
 * @member {Boolean} haveDocument
 */
FindEventInfoDto.prototype['haveDocument'] = undefined;






export default FindEventInfoDto;

