/**
 * Nex Event API
 * Utilize essa documentação para realizar a integração com o nosso sistema
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FindByEmailDto model module.
 * @module model/FindByEmailDto
 * @version 1.0
 */
class FindByEmailDto {
    /**
     * Constructs a new <code>FindByEmailDto</code>.
     * @alias module:model/FindByEmailDto
     * @param id {String} 
     * @param name {String} 
     * @param email {String} 
     * @param phoneNumber {String} 
     * @param phoneCountry {String} 
     * @param city {String} 
     * @param country {String} 
     * @param state {String} 
     * @param document {String} 
     */
    constructor(id, name, email, phoneNumber, phoneCountry, city, country, state, document) { 
        
        FindByEmailDto.initialize(this, id, name, email, phoneNumber, phoneCountry, city, country, state, document);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, email, phoneNumber, phoneCountry, city, country, state, document) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['email'] = email;
        obj['phoneNumber'] = phoneNumber;
        obj['phoneCountry'] = phoneCountry;
        obj['city'] = city;
        obj['country'] = country;
        obj['state'] = state;
        obj['document'] = document;
    }

    /**
     * Constructs a <code>FindByEmailDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FindByEmailDto} obj Optional instance to populate.
     * @return {module:model/FindByEmailDto} The populated <code>FindByEmailDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FindByEmailDto();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('phoneNumber')) {
                obj['phoneNumber'] = ApiClient.convertToType(data['phoneNumber'], 'String');
            }
            if (data.hasOwnProperty('phoneCountry')) {
                obj['phoneCountry'] = ApiClient.convertToType(data['phoneCountry'], 'String');
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('document')) {
                obj['document'] = ApiClient.convertToType(data['document'], 'String');
            }
            if (data.hasOwnProperty('validAt')) {
                obj['validAt'] = ApiClient.convertToType(data['validAt'], Object);
            }
            if (data.hasOwnProperty('userFace')) {
                obj['userFace'] = ApiClient.convertToType(data['userFace'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FindByEmailDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FindByEmailDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of FindByEmailDto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['phoneNumber'] && !(typeof data['phoneNumber'] === 'string' || data['phoneNumber'] instanceof String)) {
            throw new Error("Expected the field `phoneNumber` to be a primitive type in the JSON string but got " + data['phoneNumber']);
        }
        // ensure the json data is a string
        if (data['phoneCountry'] && !(typeof data['phoneCountry'] === 'string' || data['phoneCountry'] instanceof String)) {
            throw new Error("Expected the field `phoneCountry` to be a primitive type in the JSON string but got " + data['phoneCountry']);
        }
        // ensure the json data is a string
        if (data['city'] && !(typeof data['city'] === 'string' || data['city'] instanceof String)) {
            throw new Error("Expected the field `city` to be a primitive type in the JSON string but got " + data['city']);
        }
        // ensure the json data is a string
        if (data['country'] && !(typeof data['country'] === 'string' || data['country'] instanceof String)) {
            throw new Error("Expected the field `country` to be a primitive type in the JSON string but got " + data['country']);
        }
        // ensure the json data is a string
        if (data['state'] && !(typeof data['state'] === 'string' || data['state'] instanceof String)) {
            throw new Error("Expected the field `state` to be a primitive type in the JSON string but got " + data['state']);
        }
        // ensure the json data is a string
        if (data['document'] && !(typeof data['document'] === 'string' || data['document'] instanceof String)) {
            throw new Error("Expected the field `document` to be a primitive type in the JSON string but got " + data['document']);
        }
        // ensure the json data is a string
        if (data['userFace'] && !(typeof data['userFace'] === 'string' || data['userFace'] instanceof String)) {
            throw new Error("Expected the field `userFace` to be a primitive type in the JSON string but got " + data['userFace']);
        }

        return true;
    }


}

FindByEmailDto.RequiredProperties = ["id", "name", "email", "phoneNumber", "phoneCountry", "city", "country", "state", "document"];

/**
 * @member {String} id
 */
FindByEmailDto.prototype['id'] = undefined;

/**
 * @member {String} name
 */
FindByEmailDto.prototype['name'] = undefined;

/**
 * @member {String} email
 */
FindByEmailDto.prototype['email'] = undefined;

/**
 * @member {String} phoneNumber
 */
FindByEmailDto.prototype['phoneNumber'] = undefined;

/**
 * @member {String} phoneCountry
 */
FindByEmailDto.prototype['phoneCountry'] = undefined;

/**
 * @member {String} city
 */
FindByEmailDto.prototype['city'] = undefined;

/**
 * @member {String} country
 */
FindByEmailDto.prototype['country'] = undefined;

/**
 * @member {String} state
 */
FindByEmailDto.prototype['state'] = undefined;

/**
 * @member {String} document
 */
FindByEmailDto.prototype['document'] = undefined;

/**
 * @member {Object} validAt
 */
FindByEmailDto.prototype['validAt'] = undefined;

/**
 * @member {String} userFace
 */
FindByEmailDto.prototype['userFace'] = undefined;






export default FindByEmailDto;

