/**
 * Nex Event API
 * Utilize essa documentação para realizar a integração com o nosso sistema
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GeneralDashboardResponseDtoBestEventsInner model module.
 * @module model/GeneralDashboardResponseDtoBestEventsInner
 * @version 1.0
 */
class GeneralDashboardResponseDtoBestEventsInner {
    /**
     * Constructs a new <code>GeneralDashboardResponseDtoBestEventsInner</code>.
     * @alias module:model/GeneralDashboardResponseDtoBestEventsInner
     * @param id {String} 
     * @param title {String} 
     * @param total {Number} 
     */
    constructor(id, title, total) { 
        
        GeneralDashboardResponseDtoBestEventsInner.initialize(this, id, title, total);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, title, total) { 
        obj['id'] = id;
        obj['title'] = title;
        obj['total'] = total;
    }

    /**
     * Constructs a <code>GeneralDashboardResponseDtoBestEventsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GeneralDashboardResponseDtoBestEventsInner} obj Optional instance to populate.
     * @return {module:model/GeneralDashboardResponseDtoBestEventsInner} The populated <code>GeneralDashboardResponseDtoBestEventsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GeneralDashboardResponseDtoBestEventsInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GeneralDashboardResponseDtoBestEventsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GeneralDashboardResponseDtoBestEventsInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GeneralDashboardResponseDtoBestEventsInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }

        return true;
    }


}

GeneralDashboardResponseDtoBestEventsInner.RequiredProperties = ["id", "title", "total"];

/**
 * @member {String} id
 */
GeneralDashboardResponseDtoBestEventsInner.prototype['id'] = undefined;

/**
 * @member {String} title
 */
GeneralDashboardResponseDtoBestEventsInner.prototype['title'] = undefined;

/**
 * @member {Number} total
 */
GeneralDashboardResponseDtoBestEventsInner.prototype['total'] = undefined;






export default GeneralDashboardResponseDtoBestEventsInner;

