/**
 * Nex Event API
 * Utilize essa documentação para realizar a integração com o nosso sistema
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetEventsPrintAutomaticDtoInner model module.
 * @module model/GetEventsPrintAutomaticDtoInner
 * @version 1.0
 */
class GetEventsPrintAutomaticDtoInner {
    /**
     * Constructs a new <code>GetEventsPrintAutomaticDtoInner</code>.
     * @alias module:model/GetEventsPrintAutomaticDtoInner
     * @param id {String} 
     * @param title {String} 
     * @param photo {String} 
     * @param slug {String} 
     */
    constructor(id, title, photo, slug) { 
        
        GetEventsPrintAutomaticDtoInner.initialize(this, id, title, photo, slug);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, title, photo, slug) { 
        obj['id'] = id;
        obj['title'] = title;
        obj['photo'] = photo;
        obj['slug'] = slug;
    }

    /**
     * Constructs a <code>GetEventsPrintAutomaticDtoInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetEventsPrintAutomaticDtoInner} obj Optional instance to populate.
     * @return {module:model/GetEventsPrintAutomaticDtoInner} The populated <code>GetEventsPrintAutomaticDtoInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetEventsPrintAutomaticDtoInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('photo')) {
                obj['photo'] = ApiClient.convertToType(data['photo'], 'String');
            }
            if (data.hasOwnProperty('slug')) {
                obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetEventsPrintAutomaticDtoInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetEventsPrintAutomaticDtoInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GetEventsPrintAutomaticDtoInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['photo'] && !(typeof data['photo'] === 'string' || data['photo'] instanceof String)) {
            throw new Error("Expected the field `photo` to be a primitive type in the JSON string but got " + data['photo']);
        }
        // ensure the json data is a string
        if (data['slug'] && !(typeof data['slug'] === 'string' || data['slug'] instanceof String)) {
            throw new Error("Expected the field `slug` to be a primitive type in the JSON string but got " + data['slug']);
        }

        return true;
    }


}

GetEventsPrintAutomaticDtoInner.RequiredProperties = ["id", "title", "photo", "slug"];

/**
 * @member {String} id
 */
GetEventsPrintAutomaticDtoInner.prototype['id'] = undefined;

/**
 * @member {String} title
 */
GetEventsPrintAutomaticDtoInner.prototype['title'] = undefined;

/**
 * @member {String} photo
 */
GetEventsPrintAutomaticDtoInner.prototype['photo'] = undefined;

/**
 * @member {String} slug
 */
GetEventsPrintAutomaticDtoInner.prototype['slug'] = undefined;






export default GetEventsPrintAutomaticDtoInner;

