/**
 * Nex Event API
 * Utilize essa documentação para realizar a integração com o nosso sistema
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The QuizCreateResponseDto model module.
 * @module model/QuizCreateResponseDto
 * @version 1.0
 */
class QuizCreateResponseDto {
    /**
     * Constructs a new <code>QuizCreateResponseDto</code>.
     * @alias module:model/QuizCreateResponseDto
     * @param ok {String} 
     */
    constructor(ok) { 
        
        QuizCreateResponseDto.initialize(this, ok);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, ok) { 
        obj['ok'] = ok;
    }

    /**
     * Constructs a <code>QuizCreateResponseDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/QuizCreateResponseDto} obj Optional instance to populate.
     * @return {module:model/QuizCreateResponseDto} The populated <code>QuizCreateResponseDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QuizCreateResponseDto();

            if (data.hasOwnProperty('ok')) {
                obj['ok'] = ApiClient.convertToType(data['ok'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>QuizCreateResponseDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>QuizCreateResponseDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of QuizCreateResponseDto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['ok'] && !(typeof data['ok'] === 'string' || data['ok'] instanceof String)) {
            throw new Error("Expected the field `ok` to be a primitive type in the JSON string but got " + data['ok']);
        }

        return true;
    }


}

QuizCreateResponseDto.RequiredProperties = ["ok"];

/**
 * @member {String} ok
 */
QuizCreateResponseDto.prototype['ok'] = undefined;






export default QuizCreateResponseDto;

