/**
 * Nex Event API
 * Utilize essa documentação para realizar a integração com o nosso sistema
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import QuizDtoQuestionsInnerOptionsInner from './QuizDtoQuestionsInnerOptionsInner';

/**
 * The QuizDtoQuestionsInner model module.
 * @module model/QuizDtoQuestionsInner
 * @version 1.0
 */
class QuizDtoQuestionsInner {
    /**
     * Constructs a new <code>QuizDtoQuestionsInner</code>.
     * @alias module:model/QuizDtoQuestionsInner
     * @param questionId {String} 
     * @param description {String} 
     * @param sequential {Number} 
     * @param questionType {module:model/QuizDtoQuestionsInner.QuestionTypeEnum} 
     * @param isMandatory {Boolean} 
     * @param multipleChoice {Boolean} 
     */
    constructor(questionId, description, sequential, questionType, isMandatory, multipleChoice) { 
        
        QuizDtoQuestionsInner.initialize(this, questionId, description, sequential, questionType, isMandatory, multipleChoice);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, questionId, description, sequential, questionType, isMandatory, multipleChoice) { 
        obj['questionId'] = questionId;
        obj['description'] = description;
        obj['sequential'] = sequential;
        obj['questionType'] = questionType;
        obj['isMandatory'] = isMandatory;
        obj['multipleChoice'] = multipleChoice;
    }

    /**
     * Constructs a <code>QuizDtoQuestionsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/QuizDtoQuestionsInner} obj Optional instance to populate.
     * @return {module:model/QuizDtoQuestionsInner} The populated <code>QuizDtoQuestionsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QuizDtoQuestionsInner();

            if (data.hasOwnProperty('questionId')) {
                obj['questionId'] = ApiClient.convertToType(data['questionId'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('sequential')) {
                obj['sequential'] = ApiClient.convertToType(data['sequential'], 'Number');
            }
            if (data.hasOwnProperty('questionType')) {
                obj['questionType'] = ApiClient.convertToType(data['questionType'], 'String');
            }
            if (data.hasOwnProperty('isMandatory')) {
                obj['isMandatory'] = ApiClient.convertToType(data['isMandatory'], 'Boolean');
            }
            if (data.hasOwnProperty('multipleChoice')) {
                obj['multipleChoice'] = ApiClient.convertToType(data['multipleChoice'], 'Boolean');
            }
            if (data.hasOwnProperty('options')) {
                obj['options'] = ApiClient.convertToType(data['options'], [QuizDtoQuestionsInnerOptionsInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>QuizDtoQuestionsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>QuizDtoQuestionsInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of QuizDtoQuestionsInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['questionId'] && !(typeof data['questionId'] === 'string' || data['questionId'] instanceof String)) {
            throw new Error("Expected the field `questionId` to be a primitive type in the JSON string but got " + data['questionId']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['questionType'] && !(typeof data['questionType'] === 'string' || data['questionType'] instanceof String)) {
            throw new Error("Expected the field `questionType` to be a primitive type in the JSON string but got " + data['questionType']);
        }
        if (data['options']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['options'])) {
                throw new Error("Expected the field `options` to be an array in the JSON data but got " + data['options']);
            }
            // validate the optional field `options` (array)
            for (const item of data['options']) {
                QuizDtoQuestionsInnerOptionsInner.validateJSON(item);
            };
        }

        return true;
    }


}

QuizDtoQuestionsInner.RequiredProperties = ["questionId", "description", "sequential", "questionType", "isMandatory", "multipleChoice"];

/**
 * @member {String} questionId
 */
QuizDtoQuestionsInner.prototype['questionId'] = undefined;

/**
 * @member {String} description
 */
QuizDtoQuestionsInner.prototype['description'] = undefined;

/**
 * @member {Number} sequential
 */
QuizDtoQuestionsInner.prototype['sequential'] = undefined;

/**
 * @member {module:model/QuizDtoQuestionsInner.QuestionTypeEnum} questionType
 */
QuizDtoQuestionsInner.prototype['questionType'] = undefined;

/**
 * @member {Boolean} isMandatory
 */
QuizDtoQuestionsInner.prototype['isMandatory'] = undefined;

/**
 * @member {Boolean} multipleChoice
 */
QuizDtoQuestionsInner.prototype['multipleChoice'] = undefined;

/**
 * @member {Array.<module:model/QuizDtoQuestionsInnerOptionsInner>} options
 */
QuizDtoQuestionsInner.prototype['options'] = undefined;





/**
 * Allowed values for the <code>questionType</code> property.
 * @enum {String}
 * @readonly
 */
QuizDtoQuestionsInner['QuestionTypeEnum'] = {

    /**
     * value: "MULTIPLE_CHOICE"
     * @const
     */
    "MULTIPLE_CHOICE": "MULTIPLE_CHOICE",

    /**
     * value: "RATING"
     * @const
     */
    "RATING": "RATING",

    /**
     * value: "DESCRIPTIVE"
     * @const
     */
    "DESCRIPTIVE": "DESCRIPTIVE"
};



export default QuizDtoQuestionsInner;

