/**
 * Nex Event API
 * Utilize essa documentação para realizar a integração com o nosso sistema
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AuthLoginDto from './model/AuthLoginDto';
import CreateParticipantQuizDto from './model/CreateParticipantQuizDto';
import CreateParticipantQuizDtoResponsesInner from './model/CreateParticipantQuizDtoResponsesInner';
import CreateSponsorUserDto from './model/CreateSponsorUserDto';
import EventAllResponseDtoInner from './model/EventAllResponseDtoInner';
import EventCreateDto from './model/EventCreateDto';
import EventCreateDtoEventConfig from './model/EventCreateDtoEventConfig';
import EventCreateDtoEventScheduleInner from './model/EventCreateDtoEventScheduleInner';
import EventCreateDtoEventTicketsInner from './model/EventCreateDtoEventTicketsInner';
import EventCreateDtoEventTicketsInnerEventTicketBonusesInner from './model/EventCreateDtoEventTicketsInnerEventTicketBonusesInner';
import EventCreateDtoEventTicketsInnerEventTicketDaysInner from './model/EventCreateDtoEventTicketsInnerEventTicketDaysInner';
import EventCreateDtoEventTicketsInnerEventTicketPricesInner from './model/EventCreateDtoEventTicketsInnerEventTicketPricesInner';
import EventDashboardPanelFinancialDto from './model/EventDashboardPanelFinancialDto';
import EventDashboardPanelFinancialDtoSellDiaryByTicketInner from './model/EventDashboardPanelFinancialDtoSellDiaryByTicketInner';
import EventDashboardResponseDto from './model/EventDashboardResponseDto';
import EventDashboardResponseDtoEventTicketPercentualSellInner from './model/EventDashboardResponseDtoEventTicketPercentualSellInner';
import EventDashboardResponseDtoEventTicketsInner from './model/EventDashboardResponseDtoEventTicketsInner';
import EventDashboardResponseDtoSellDiaryInner from './model/EventDashboardResponseDtoSellDiaryInner';
import EventNetworksProducerCreateDtoInner from './model/EventNetworksProducerCreateDtoInner';
import EventNetworksProducerResponseDtoInner from './model/EventNetworksProducerResponseDtoInner';
import EventNetworksResponse from './model/EventNetworksResponse';
import EventParticipantCreateDto from './model/EventParticipantCreateDto';
import EventParticipantCreateDtoNetworksInner from './model/EventParticipantCreateDtoNetworksInner';
import EventParticipantResponseDto from './model/EventParticipantResponseDto';
import EventParticipantResponseDtoQuestionsResponsesInner from './model/EventParticipantResponseDtoQuestionsResponsesInner';
import EventParticipantResponseDtoQuestionsResponsesInnerEventQuizQuestionOptionInner from './model/EventParticipantResponseDtoQuestionsResponsesInnerEventQuizQuestionOptionInner';
import EventParticipantsResponseDtoInner from './model/EventParticipantsResponseDtoInner';
import EventPrintAllPartsDtoInner from './model/EventPrintAllPartsDtoInner';
import EventProducerCreateStaffDto from './model/EventProducerCreateStaffDto';
import EventProducerRecommendedStaffDto from './model/EventProducerRecommendedStaffDto';
import EventProducerRecommendedStaffDtoEventsInner from './model/EventProducerRecommendedStaffDtoEventsInner';
import EventProducerRecommendedStaffs from './model/EventProducerRecommendedStaffs';
import EventProducerResponseListStaffDtoInner from './model/EventProducerResponseListStaffDtoInner';
import EventProducerUpdateDto from './model/EventProducerUpdateDto';
import EventQuizCreateDto from './model/EventQuizCreateDto';
import EventQuizCreateDtoQuestionsInner from './model/EventQuizCreateDtoQuestionsInner';
import EventQuizCreateDtoQuestionsInnerQuestionOptionsInner from './model/EventQuizCreateDtoQuestionsInnerQuestionOptionsInner';
import EventQuizCreatedResponseDto from './model/EventQuizCreatedResponseDto';
import EventQuizDashboarDto from './model/EventQuizDashboarDto';
import EventQuizDashboarDtoMultipleChoiceInner from './model/EventQuizDashboarDtoMultipleChoiceInner';
import EventQuizDashboarDtoMultipleChoiceInnerOptionsInner from './model/EventQuizDashboarDtoMultipleChoiceInnerOptionsInner';
import EventQuizDashboarDtoRatingInner from './model/EventQuizDashboarDtoRatingInner';
import EventQuizDashboarDtoRatingInnerRatingsInner from './model/EventQuizDashboarDtoRatingInnerRatingsInner';
import EventQuizFindAllResponse from './model/EventQuizFindAllResponse';
import EventQuizFindAllResponseDtoInner from './model/EventQuizFindAllResponseDtoInner';
import EventQuizParticipantsResponse from './model/EventQuizParticipantsResponse';
import EventQuizParticipantsResponseDtoInner from './model/EventQuizParticipantsResponseDtoInner';
import EventStaffAllResponseDtoInner from './model/EventStaffAllResponseDtoInner';
import EventStaffsResponse from './model/EventStaffsResponse';
import EventTicketCouponDashboardDto from './model/EventTicketCouponDashboardDto';
import EventTicketCouponResponseDto from './model/EventTicketCouponResponseDto';
import EventTicketCouponsDto from './model/EventTicketCouponsDto';
import EventTicketCouponsDtoEventTicketsIdInner from './model/EventTicketCouponsDtoEventTicketsIdInner';
import EventTicketCouponsResponse from './model/EventTicketCouponsResponse';
import EventTicketCreateDto from './model/EventTicketCreateDto';
import EventTicketDashboardResponseDtoInner from './model/EventTicketDashboardResponseDtoInner';
import EventTicketDashboardResponseDtoInnerTicketBatchInner from './model/EventTicketDashboardResponseDtoInnerTicketBatchInner';
import EventTicketDashboardResponseDtoInnerTicketBatchInnerLinkInner from './model/EventTicketDashboardResponseDtoInnerTicketBatchInnerLinkInner';
import EventTicketInfoDto from './model/EventTicketInfoDto';
import EventTicketInfoDtoGuestsInner from './model/EventTicketInfoDtoGuestsInner';
import EventTicketInfoDtoTicketsInner from './model/EventTicketInfoDtoTicketsInner';
import EventTicketInfoDtoTicketsInnerTicketGiftsInner from './model/EventTicketInfoDtoTicketsInnerTicketGiftsInner';
import EventTicketLinkByEmailResponse from './model/EventTicketLinkByEmailResponse';
import EventTicketLinkByEmailResponseDto from './model/EventTicketLinkByEmailResponseDto';
import EventTicketLinkByEmailResponseDtoUncompletedInner from './model/EventTicketLinkByEmailResponseDtoUncompletedInner';
import EventTicketLinkByEmailResponseDtoUsersInner from './model/EventTicketLinkByEmailResponseDtoUsersInner';
import EventTicketLinkCreateResponseDto from './model/EventTicketLinkCreateResponseDto';
import EventTicketLinkResponse from './model/EventTicketLinkResponse';
import EventTicketLinkResponseDtoInner from './model/EventTicketLinkResponseDtoInner';
import EventTicketLinkResponseDtoInnerParticipantInner from './model/EventTicketLinkResponseDtoInnerParticipantInner';
import EventTicketSellDto from './model/EventTicketSellDto';
import EventTicketSellDtoEventTicketsInner from './model/EventTicketSellDtoEventTicketsInner';
import EventTicketSellDtoUser from './model/EventTicketSellDtoUser';
import EventTicketUpdateDto from './model/EventTicketUpdateDto';
import EventTicketsResponse from './model/EventTicketsResponse';
import FindAllPublicEvents from './model/FindAllPublicEvents';
import FindAllPublicEventsDtoInner from './model/FindAllPublicEventsDtoInner';
import FindByEmailDto from './model/FindByEmailDto';
import FindByFacialResponseDto from './model/FindByFacialResponseDto';
import FindByFacialResponseDtoTicketsInner from './model/FindByFacialResponseDtoTicketsInner';
import FindEventInfoDto from './model/FindEventInfoDto';
import FindOneDashboardParticipantPanelDto from './model/FindOneDashboardParticipantPanelDto';
import FindOneDashboardParticipantPanelDtoEventAverageLocationInner from './model/FindOneDashboardParticipantPanelDtoEventAverageLocationInner';
import FindOnePublicEventsDto from './model/FindOnePublicEventsDto';
import FindOnePublicEventsDtoConfig from './model/FindOnePublicEventsDtoConfig';
import FindOnePublicEventsDtoTerm from './model/FindOnePublicEventsDtoTerm';
import FindOnePublicEventsDtoTicketInner from './model/FindOnePublicEventsDtoTicketInner';
import FindOnePublicEventsDtoTicketInnerTicketDaysInner from './model/FindOnePublicEventsDtoTicketInnerTicketDaysInner';
import FindTicketByLinkResponseDto from './model/FindTicketByLinkResponseDto';
import FindTicketByLinkResponseDtoTicketDaysInner from './model/FindTicketByLinkResponseDtoTicketDaysInner';
import GeneralDashboardResponseDto from './model/GeneralDashboardResponseDto';
import GeneralDashboardResponseDtoBestEventsInner from './model/GeneralDashboardResponseDtoBestEventsInner';
import GetEventConfigDto from './model/GetEventConfigDto';
import GetEventsPrintAutomatic from './model/GetEventsPrintAutomatic';
import GetEventsPrintAutomaticDtoInner from './model/GetEventsPrintAutomaticDtoInner';
import LastAccreditedParticipantsDtoInner from './model/LastAccreditedParticipantsDtoInner';
import LastAccreditedParticipantsResponse from './model/LastAccreditedParticipantsResponse';
import ListTickets from './model/ListTickets';
import ListTicketsDtoInner from './model/ListTicketsDtoInner';
import LoginResponseDto from './model/LoginResponseDto';
import PaginationResponse from './model/PaginationResponse';
import ParticipantSocialNetworDto from './model/ParticipantSocialNetworDto';
import ParticipantSocialNetworks from './model/ParticipantSocialNetworks';
import ParticipantTicketDto from './model/ParticipantTicketDto';
import QuizCreateResponseDto from './model/QuizCreateResponseDto';
import QuizDto from './model/QuizDto';
import QuizDtoQuestionsInner from './model/QuizDtoQuestionsInner';
import QuizDtoQuestionsInnerOptionsInner from './model/QuizDtoQuestionsInnerOptionsInner';
import ResponseEventParticipants from './model/ResponseEventParticipants';
import ResponseSponsorUserDto from './model/ResponseSponsorUserDto';
import ResponseStaffEvents from './model/ResponseStaffEvents';
import ThanksScreenDto from './model/ThanksScreenDto';
import UpdateSponsorUserDto from './model/UpdateSponsorUserDto';
import UserIsParticipantInEventByLinkIdResponseDto from './model/UserIsParticipantInEventByLinkIdResponseDto';
import UserProducerCreateDto from './model/UserProducerCreateDto';
import UserProducerFinishSignUpDto from './model/UserProducerFinishSignUpDto';
import UserProducerResponseDto from './model/UserProducerResponseDto';
import UserProducerResponseDtoEventsInner from './model/UserProducerResponseDtoEventsInner';
import AuthApi from './api/AuthApi';
import EventParticipantApi from './api/EventParticipantApi';
import EventProducerApi from './api/EventProducerApi';
import EventProducerCredentialApi from './api/EventProducerCredentialApi';
import EventProducerNetworksApi from './api/EventProducerNetworksApi';
import EventProducerStaffApi from './api/EventProducerStaffApi';
import EventProducerTicketsApi from './api/EventProducerTicketsApi';
import EventQuizApi from './api/EventQuizApi';
import OtpApi from './api/OtpApi';
import SponsorUserApi from './api/SponsorUserApi';
import UserProducerApi from './api/UserProducerApi';


/**
* Utilize essa documentação para realizar a integração com o nosso sistema.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var NexEventApi = require('index'); // See note below*.
* var xxxSvc = new NexEventApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new NexEventApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new NexEventApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new NexEventApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AuthLoginDto model constructor.
     * @property {module:model/AuthLoginDto}
     */
    AuthLoginDto,

    /**
     * The CreateParticipantQuizDto model constructor.
     * @property {module:model/CreateParticipantQuizDto}
     */
    CreateParticipantQuizDto,

    /**
     * The CreateParticipantQuizDtoResponsesInner model constructor.
     * @property {module:model/CreateParticipantQuizDtoResponsesInner}
     */
    CreateParticipantQuizDtoResponsesInner,

    /**
     * The CreateSponsorUserDto model constructor.
     * @property {module:model/CreateSponsorUserDto}
     */
    CreateSponsorUserDto,

    /**
     * The EventAllResponseDtoInner model constructor.
     * @property {module:model/EventAllResponseDtoInner}
     */
    EventAllResponseDtoInner,

    /**
     * The EventCreateDto model constructor.
     * @property {module:model/EventCreateDto}
     */
    EventCreateDto,

    /**
     * The EventCreateDtoEventConfig model constructor.
     * @property {module:model/EventCreateDtoEventConfig}
     */
    EventCreateDtoEventConfig,

    /**
     * The EventCreateDtoEventScheduleInner model constructor.
     * @property {module:model/EventCreateDtoEventScheduleInner}
     */
    EventCreateDtoEventScheduleInner,

    /**
     * The EventCreateDtoEventTicketsInner model constructor.
     * @property {module:model/EventCreateDtoEventTicketsInner}
     */
    EventCreateDtoEventTicketsInner,

    /**
     * The EventCreateDtoEventTicketsInnerEventTicketBonusesInner model constructor.
     * @property {module:model/EventCreateDtoEventTicketsInnerEventTicketBonusesInner}
     */
    EventCreateDtoEventTicketsInnerEventTicketBonusesInner,

    /**
     * The EventCreateDtoEventTicketsInnerEventTicketDaysInner model constructor.
     * @property {module:model/EventCreateDtoEventTicketsInnerEventTicketDaysInner}
     */
    EventCreateDtoEventTicketsInnerEventTicketDaysInner,

    /**
     * The EventCreateDtoEventTicketsInnerEventTicketPricesInner model constructor.
     * @property {module:model/EventCreateDtoEventTicketsInnerEventTicketPricesInner}
     */
    EventCreateDtoEventTicketsInnerEventTicketPricesInner,

    /**
     * The EventDashboardPanelFinancialDto model constructor.
     * @property {module:model/EventDashboardPanelFinancialDto}
     */
    EventDashboardPanelFinancialDto,

    /**
     * The EventDashboardPanelFinancialDtoSellDiaryByTicketInner model constructor.
     * @property {module:model/EventDashboardPanelFinancialDtoSellDiaryByTicketInner}
     */
    EventDashboardPanelFinancialDtoSellDiaryByTicketInner,

    /**
     * The EventDashboardResponseDto model constructor.
     * @property {module:model/EventDashboardResponseDto}
     */
    EventDashboardResponseDto,

    /**
     * The EventDashboardResponseDtoEventTicketPercentualSellInner model constructor.
     * @property {module:model/EventDashboardResponseDtoEventTicketPercentualSellInner}
     */
    EventDashboardResponseDtoEventTicketPercentualSellInner,

    /**
     * The EventDashboardResponseDtoEventTicketsInner model constructor.
     * @property {module:model/EventDashboardResponseDtoEventTicketsInner}
     */
    EventDashboardResponseDtoEventTicketsInner,

    /**
     * The EventDashboardResponseDtoSellDiaryInner model constructor.
     * @property {module:model/EventDashboardResponseDtoSellDiaryInner}
     */
    EventDashboardResponseDtoSellDiaryInner,

    /**
     * The EventNetworksProducerCreateDtoInner model constructor.
     * @property {module:model/EventNetworksProducerCreateDtoInner}
     */
    EventNetworksProducerCreateDtoInner,

    /**
     * The EventNetworksProducerResponseDtoInner model constructor.
     * @property {module:model/EventNetworksProducerResponseDtoInner}
     */
    EventNetworksProducerResponseDtoInner,

    /**
     * The EventNetworksResponse model constructor.
     * @property {module:model/EventNetworksResponse}
     */
    EventNetworksResponse,

    /**
     * The EventParticipantCreateDto model constructor.
     * @property {module:model/EventParticipantCreateDto}
     */
    EventParticipantCreateDto,

    /**
     * The EventParticipantCreateDtoNetworksInner model constructor.
     * @property {module:model/EventParticipantCreateDtoNetworksInner}
     */
    EventParticipantCreateDtoNetworksInner,

    /**
     * The EventParticipantResponseDto model constructor.
     * @property {module:model/EventParticipantResponseDto}
     */
    EventParticipantResponseDto,

    /**
     * The EventParticipantResponseDtoQuestionsResponsesInner model constructor.
     * @property {module:model/EventParticipantResponseDtoQuestionsResponsesInner}
     */
    EventParticipantResponseDtoQuestionsResponsesInner,

    /**
     * The EventParticipantResponseDtoQuestionsResponsesInnerEventQuizQuestionOptionInner model constructor.
     * @property {module:model/EventParticipantResponseDtoQuestionsResponsesInnerEventQuizQuestionOptionInner}
     */
    EventParticipantResponseDtoQuestionsResponsesInnerEventQuizQuestionOptionInner,

    /**
     * The EventParticipantsResponseDtoInner model constructor.
     * @property {module:model/EventParticipantsResponseDtoInner}
     */
    EventParticipantsResponseDtoInner,

    /**
     * The EventPrintAllPartsDtoInner model constructor.
     * @property {module:model/EventPrintAllPartsDtoInner}
     */
    EventPrintAllPartsDtoInner,

    /**
     * The EventProducerCreateStaffDto model constructor.
     * @property {module:model/EventProducerCreateStaffDto}
     */
    EventProducerCreateStaffDto,

    /**
     * The EventProducerRecommendedStaffDto model constructor.
     * @property {module:model/EventProducerRecommendedStaffDto}
     */
    EventProducerRecommendedStaffDto,

    /**
     * The EventProducerRecommendedStaffDtoEventsInner model constructor.
     * @property {module:model/EventProducerRecommendedStaffDtoEventsInner}
     */
    EventProducerRecommendedStaffDtoEventsInner,

    /**
     * The EventProducerRecommendedStaffs model constructor.
     * @property {module:model/EventProducerRecommendedStaffs}
     */
    EventProducerRecommendedStaffs,

    /**
     * The EventProducerResponseListStaffDtoInner model constructor.
     * @property {module:model/EventProducerResponseListStaffDtoInner}
     */
    EventProducerResponseListStaffDtoInner,

    /**
     * The EventProducerUpdateDto model constructor.
     * @property {module:model/EventProducerUpdateDto}
     */
    EventProducerUpdateDto,

    /**
     * The EventQuizCreateDto model constructor.
     * @property {module:model/EventQuizCreateDto}
     */
    EventQuizCreateDto,

    /**
     * The EventQuizCreateDtoQuestionsInner model constructor.
     * @property {module:model/EventQuizCreateDtoQuestionsInner}
     */
    EventQuizCreateDtoQuestionsInner,

    /**
     * The EventQuizCreateDtoQuestionsInnerQuestionOptionsInner model constructor.
     * @property {module:model/EventQuizCreateDtoQuestionsInnerQuestionOptionsInner}
     */
    EventQuizCreateDtoQuestionsInnerQuestionOptionsInner,

    /**
     * The EventQuizCreatedResponseDto model constructor.
     * @property {module:model/EventQuizCreatedResponseDto}
     */
    EventQuizCreatedResponseDto,

    /**
     * The EventQuizDashboarDto model constructor.
     * @property {module:model/EventQuizDashboarDto}
     */
    EventQuizDashboarDto,

    /**
     * The EventQuizDashboarDtoMultipleChoiceInner model constructor.
     * @property {module:model/EventQuizDashboarDtoMultipleChoiceInner}
     */
    EventQuizDashboarDtoMultipleChoiceInner,

    /**
     * The EventQuizDashboarDtoMultipleChoiceInnerOptionsInner model constructor.
     * @property {module:model/EventQuizDashboarDtoMultipleChoiceInnerOptionsInner}
     */
    EventQuizDashboarDtoMultipleChoiceInnerOptionsInner,

    /**
     * The EventQuizDashboarDtoRatingInner model constructor.
     * @property {module:model/EventQuizDashboarDtoRatingInner}
     */
    EventQuizDashboarDtoRatingInner,

    /**
     * The EventQuizDashboarDtoRatingInnerRatingsInner model constructor.
     * @property {module:model/EventQuizDashboarDtoRatingInnerRatingsInner}
     */
    EventQuizDashboarDtoRatingInnerRatingsInner,

    /**
     * The EventQuizFindAllResponse model constructor.
     * @property {module:model/EventQuizFindAllResponse}
     */
    EventQuizFindAllResponse,

    /**
     * The EventQuizFindAllResponseDtoInner model constructor.
     * @property {module:model/EventQuizFindAllResponseDtoInner}
     */
    EventQuizFindAllResponseDtoInner,

    /**
     * The EventQuizParticipantsResponse model constructor.
     * @property {module:model/EventQuizParticipantsResponse}
     */
    EventQuizParticipantsResponse,

    /**
     * The EventQuizParticipantsResponseDtoInner model constructor.
     * @property {module:model/EventQuizParticipantsResponseDtoInner}
     */
    EventQuizParticipantsResponseDtoInner,

    /**
     * The EventStaffAllResponseDtoInner model constructor.
     * @property {module:model/EventStaffAllResponseDtoInner}
     */
    EventStaffAllResponseDtoInner,

    /**
     * The EventStaffsResponse model constructor.
     * @property {module:model/EventStaffsResponse}
     */
    EventStaffsResponse,

    /**
     * The EventTicketCouponDashboardDto model constructor.
     * @property {module:model/EventTicketCouponDashboardDto}
     */
    EventTicketCouponDashboardDto,

    /**
     * The EventTicketCouponResponseDto model constructor.
     * @property {module:model/EventTicketCouponResponseDto}
     */
    EventTicketCouponResponseDto,

    /**
     * The EventTicketCouponsDto model constructor.
     * @property {module:model/EventTicketCouponsDto}
     */
    EventTicketCouponsDto,

    /**
     * The EventTicketCouponsDtoEventTicketsIdInner model constructor.
     * @property {module:model/EventTicketCouponsDtoEventTicketsIdInner}
     */
    EventTicketCouponsDtoEventTicketsIdInner,

    /**
     * The EventTicketCouponsResponse model constructor.
     * @property {module:model/EventTicketCouponsResponse}
     */
    EventTicketCouponsResponse,

    /**
     * The EventTicketCreateDto model constructor.
     * @property {module:model/EventTicketCreateDto}
     */
    EventTicketCreateDto,

    /**
     * The EventTicketDashboardResponseDtoInner model constructor.
     * @property {module:model/EventTicketDashboardResponseDtoInner}
     */
    EventTicketDashboardResponseDtoInner,

    /**
     * The EventTicketDashboardResponseDtoInnerTicketBatchInner model constructor.
     * @property {module:model/EventTicketDashboardResponseDtoInnerTicketBatchInner}
     */
    EventTicketDashboardResponseDtoInnerTicketBatchInner,

    /**
     * The EventTicketDashboardResponseDtoInnerTicketBatchInnerLinkInner model constructor.
     * @property {module:model/EventTicketDashboardResponseDtoInnerTicketBatchInnerLinkInner}
     */
    EventTicketDashboardResponseDtoInnerTicketBatchInnerLinkInner,

    /**
     * The EventTicketInfoDto model constructor.
     * @property {module:model/EventTicketInfoDto}
     */
    EventTicketInfoDto,

    /**
     * The EventTicketInfoDtoGuestsInner model constructor.
     * @property {module:model/EventTicketInfoDtoGuestsInner}
     */
    EventTicketInfoDtoGuestsInner,

    /**
     * The EventTicketInfoDtoTicketsInner model constructor.
     * @property {module:model/EventTicketInfoDtoTicketsInner}
     */
    EventTicketInfoDtoTicketsInner,

    /**
     * The EventTicketInfoDtoTicketsInnerTicketGiftsInner model constructor.
     * @property {module:model/EventTicketInfoDtoTicketsInnerTicketGiftsInner}
     */
    EventTicketInfoDtoTicketsInnerTicketGiftsInner,

    /**
     * The EventTicketLinkByEmailResponse model constructor.
     * @property {module:model/EventTicketLinkByEmailResponse}
     */
    EventTicketLinkByEmailResponse,

    /**
     * The EventTicketLinkByEmailResponseDto model constructor.
     * @property {module:model/EventTicketLinkByEmailResponseDto}
     */
    EventTicketLinkByEmailResponseDto,

    /**
     * The EventTicketLinkByEmailResponseDtoUncompletedInner model constructor.
     * @property {module:model/EventTicketLinkByEmailResponseDtoUncompletedInner}
     */
    EventTicketLinkByEmailResponseDtoUncompletedInner,

    /**
     * The EventTicketLinkByEmailResponseDtoUsersInner model constructor.
     * @property {module:model/EventTicketLinkByEmailResponseDtoUsersInner}
     */
    EventTicketLinkByEmailResponseDtoUsersInner,

    /**
     * The EventTicketLinkCreateResponseDto model constructor.
     * @property {module:model/EventTicketLinkCreateResponseDto}
     */
    EventTicketLinkCreateResponseDto,

    /**
     * The EventTicketLinkResponse model constructor.
     * @property {module:model/EventTicketLinkResponse}
     */
    EventTicketLinkResponse,

    /**
     * The EventTicketLinkResponseDtoInner model constructor.
     * @property {module:model/EventTicketLinkResponseDtoInner}
     */
    EventTicketLinkResponseDtoInner,

    /**
     * The EventTicketLinkResponseDtoInnerParticipantInner model constructor.
     * @property {module:model/EventTicketLinkResponseDtoInnerParticipantInner}
     */
    EventTicketLinkResponseDtoInnerParticipantInner,

    /**
     * The EventTicketSellDto model constructor.
     * @property {module:model/EventTicketSellDto}
     */
    EventTicketSellDto,

    /**
     * The EventTicketSellDtoEventTicketsInner model constructor.
     * @property {module:model/EventTicketSellDtoEventTicketsInner}
     */
    EventTicketSellDtoEventTicketsInner,

    /**
     * The EventTicketSellDtoUser model constructor.
     * @property {module:model/EventTicketSellDtoUser}
     */
    EventTicketSellDtoUser,

    /**
     * The EventTicketUpdateDto model constructor.
     * @property {module:model/EventTicketUpdateDto}
     */
    EventTicketUpdateDto,

    /**
     * The EventTicketsResponse model constructor.
     * @property {module:model/EventTicketsResponse}
     */
    EventTicketsResponse,

    /**
     * The FindAllPublicEvents model constructor.
     * @property {module:model/FindAllPublicEvents}
     */
    FindAllPublicEvents,

    /**
     * The FindAllPublicEventsDtoInner model constructor.
     * @property {module:model/FindAllPublicEventsDtoInner}
     */
    FindAllPublicEventsDtoInner,

    /**
     * The FindByEmailDto model constructor.
     * @property {module:model/FindByEmailDto}
     */
    FindByEmailDto,

    /**
     * The FindByFacialResponseDto model constructor.
     * @property {module:model/FindByFacialResponseDto}
     */
    FindByFacialResponseDto,

    /**
     * The FindByFacialResponseDtoTicketsInner model constructor.
     * @property {module:model/FindByFacialResponseDtoTicketsInner}
     */
    FindByFacialResponseDtoTicketsInner,

    /**
     * The FindEventInfoDto model constructor.
     * @property {module:model/FindEventInfoDto}
     */
    FindEventInfoDto,

    /**
     * The FindOneDashboardParticipantPanelDto model constructor.
     * @property {module:model/FindOneDashboardParticipantPanelDto}
     */
    FindOneDashboardParticipantPanelDto,

    /**
     * The FindOneDashboardParticipantPanelDtoEventAverageLocationInner model constructor.
     * @property {module:model/FindOneDashboardParticipantPanelDtoEventAverageLocationInner}
     */
    FindOneDashboardParticipantPanelDtoEventAverageLocationInner,

    /**
     * The FindOnePublicEventsDto model constructor.
     * @property {module:model/FindOnePublicEventsDto}
     */
    FindOnePublicEventsDto,

    /**
     * The FindOnePublicEventsDtoConfig model constructor.
     * @property {module:model/FindOnePublicEventsDtoConfig}
     */
    FindOnePublicEventsDtoConfig,

    /**
     * The FindOnePublicEventsDtoTerm model constructor.
     * @property {module:model/FindOnePublicEventsDtoTerm}
     */
    FindOnePublicEventsDtoTerm,

    /**
     * The FindOnePublicEventsDtoTicketInner model constructor.
     * @property {module:model/FindOnePublicEventsDtoTicketInner}
     */
    FindOnePublicEventsDtoTicketInner,

    /**
     * The FindOnePublicEventsDtoTicketInnerTicketDaysInner model constructor.
     * @property {module:model/FindOnePublicEventsDtoTicketInnerTicketDaysInner}
     */
    FindOnePublicEventsDtoTicketInnerTicketDaysInner,

    /**
     * The FindTicketByLinkResponseDto model constructor.
     * @property {module:model/FindTicketByLinkResponseDto}
     */
    FindTicketByLinkResponseDto,

    /**
     * The FindTicketByLinkResponseDtoTicketDaysInner model constructor.
     * @property {module:model/FindTicketByLinkResponseDtoTicketDaysInner}
     */
    FindTicketByLinkResponseDtoTicketDaysInner,

    /**
     * The GeneralDashboardResponseDto model constructor.
     * @property {module:model/GeneralDashboardResponseDto}
     */
    GeneralDashboardResponseDto,

    /**
     * The GeneralDashboardResponseDtoBestEventsInner model constructor.
     * @property {module:model/GeneralDashboardResponseDtoBestEventsInner}
     */
    GeneralDashboardResponseDtoBestEventsInner,

    /**
     * The GetEventConfigDto model constructor.
     * @property {module:model/GetEventConfigDto}
     */
    GetEventConfigDto,

    /**
     * The GetEventsPrintAutomatic model constructor.
     * @property {module:model/GetEventsPrintAutomatic}
     */
    GetEventsPrintAutomatic,

    /**
     * The GetEventsPrintAutomaticDtoInner model constructor.
     * @property {module:model/GetEventsPrintAutomaticDtoInner}
     */
    GetEventsPrintAutomaticDtoInner,

    /**
     * The LastAccreditedParticipantsDtoInner model constructor.
     * @property {module:model/LastAccreditedParticipantsDtoInner}
     */
    LastAccreditedParticipantsDtoInner,

    /**
     * The LastAccreditedParticipantsResponse model constructor.
     * @property {module:model/LastAccreditedParticipantsResponse}
     */
    LastAccreditedParticipantsResponse,

    /**
     * The ListTickets model constructor.
     * @property {module:model/ListTickets}
     */
    ListTickets,

    /**
     * The ListTicketsDtoInner model constructor.
     * @property {module:model/ListTicketsDtoInner}
     */
    ListTicketsDtoInner,

    /**
     * The LoginResponseDto model constructor.
     * @property {module:model/LoginResponseDto}
     */
    LoginResponseDto,

    /**
     * The PaginationResponse model constructor.
     * @property {module:model/PaginationResponse}
     */
    PaginationResponse,

    /**
     * The ParticipantSocialNetworDto model constructor.
     * @property {module:model/ParticipantSocialNetworDto}
     */
    ParticipantSocialNetworDto,

    /**
     * The ParticipantSocialNetworks model constructor.
     * @property {module:model/ParticipantSocialNetworks}
     */
    ParticipantSocialNetworks,

    /**
     * The ParticipantTicketDto model constructor.
     * @property {module:model/ParticipantTicketDto}
     */
    ParticipantTicketDto,

    /**
     * The QuizCreateResponseDto model constructor.
     * @property {module:model/QuizCreateResponseDto}
     */
    QuizCreateResponseDto,

    /**
     * The QuizDto model constructor.
     * @property {module:model/QuizDto}
     */
    QuizDto,

    /**
     * The QuizDtoQuestionsInner model constructor.
     * @property {module:model/QuizDtoQuestionsInner}
     */
    QuizDtoQuestionsInner,

    /**
     * The QuizDtoQuestionsInnerOptionsInner model constructor.
     * @property {module:model/QuizDtoQuestionsInnerOptionsInner}
     */
    QuizDtoQuestionsInnerOptionsInner,

    /**
     * The ResponseEventParticipants model constructor.
     * @property {module:model/ResponseEventParticipants}
     */
    ResponseEventParticipants,

    /**
     * The ResponseSponsorUserDto model constructor.
     * @property {module:model/ResponseSponsorUserDto}
     */
    ResponseSponsorUserDto,

    /**
     * The ResponseStaffEvents model constructor.
     * @property {module:model/ResponseStaffEvents}
     */
    ResponseStaffEvents,

    /**
     * The ThanksScreenDto model constructor.
     * @property {module:model/ThanksScreenDto}
     */
    ThanksScreenDto,

    /**
     * The UpdateSponsorUserDto model constructor.
     * @property {module:model/UpdateSponsorUserDto}
     */
    UpdateSponsorUserDto,

    /**
     * The UserIsParticipantInEventByLinkIdResponseDto model constructor.
     * @property {module:model/UserIsParticipantInEventByLinkIdResponseDto}
     */
    UserIsParticipantInEventByLinkIdResponseDto,

    /**
     * The UserProducerCreateDto model constructor.
     * @property {module:model/UserProducerCreateDto}
     */
    UserProducerCreateDto,

    /**
     * The UserProducerFinishSignUpDto model constructor.
     * @property {module:model/UserProducerFinishSignUpDto}
     */
    UserProducerFinishSignUpDto,

    /**
     * The UserProducerResponseDto model constructor.
     * @property {module:model/UserProducerResponseDto}
     */
    UserProducerResponseDto,

    /**
     * The UserProducerResponseDtoEventsInner model constructor.
     * @property {module:model/UserProducerResponseDtoEventsInner}
     */
    UserProducerResponseDtoEventsInner,

    /**
    * The AuthApi service constructor.
    * @property {module:api/AuthApi}
    */
    AuthApi,

    /**
    * The EventParticipantApi service constructor.
    * @property {module:api/EventParticipantApi}
    */
    EventParticipantApi,

    /**
    * The EventProducerApi service constructor.
    * @property {module:api/EventProducerApi}
    */
    EventProducerApi,

    /**
    * The EventProducerCredentialApi service constructor.
    * @property {module:api/EventProducerCredentialApi}
    */
    EventProducerCredentialApi,

    /**
    * The EventProducerNetworksApi service constructor.
    * @property {module:api/EventProducerNetworksApi}
    */
    EventProducerNetworksApi,

    /**
    * The EventProducerStaffApi service constructor.
    * @property {module:api/EventProducerStaffApi}
    */
    EventProducerStaffApi,

    /**
    * The EventProducerTicketsApi service constructor.
    * @property {module:api/EventProducerTicketsApi}
    */
    EventProducerTicketsApi,

    /**
    * The EventQuizApi service constructor.
    * @property {module:api/EventQuizApi}
    */
    EventQuizApi,

    /**
    * The OtpApi service constructor.
    * @property {module:api/OtpApi}
    */
    OtpApi,

    /**
    * The SponsorUserApi service constructor.
    * @property {module:api/SponsorUserApi}
    */
    SponsorUserApi,

    /**
    * The UserProducerApi service constructor.
    * @property {module:api/UserProducerApi}
    */
    UserProducerApi
};
