/**
 * Nex Event API
 * Utilize essa documentação para realizar a integração com o nosso sistema
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NexEventApi);
  }
}(this, function(expect, NexEventApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NexEventApi.EventCreateDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EventCreateDto', function() {
    it('should create an instance of EventCreateDto', function() {
      // uncomment below and update the code to test EventCreateDto
      //var instance = new NexEventApi.EventCreateDto();
      //expect(instance).to.be.a(NexEventApi.EventCreateDto);
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new NexEventApi.EventCreateDto();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new NexEventApi.EventCreateDto();
      //expect(instance).to.be();
    });

    it('should have the property eventPublic (base name: "eventPublic")', function() {
      // uncomment below and update the code to test the property eventPublic
      //var instance = new NexEventApi.EventCreateDto();
      //expect(instance).to.be();
    });

    it('should have the property startAt (base name: "startAt")', function() {
      // uncomment below and update the code to test the property startAt
      //var instance = new NexEventApi.EventCreateDto();
      //expect(instance).to.be();
    });

    it('should have the property endAt (base name: "endAt")', function() {
      // uncomment below and update the code to test the property endAt
      //var instance = new NexEventApi.EventCreateDto();
      //expect(instance).to.be();
    });

    it('should have the property startPublishAt (base name: "startPublishAt")', function() {
      // uncomment below and update the code to test the property startPublishAt
      //var instance = new NexEventApi.EventCreateDto();
      //expect(instance).to.be();
    });

    it('should have the property endPublishAt (base name: "endPublishAt")', function() {
      // uncomment below and update the code to test the property endPublishAt
      //var instance = new NexEventApi.EventCreateDto();
      //expect(instance).to.be();
    });

    it('should have the property category (base name: "category")', function() {
      // uncomment below and update the code to test the property category
      //var instance = new NexEventApi.EventCreateDto();
      //expect(instance).to.be();
    });

    it('should have the property location (base name: "location")', function() {
      // uncomment below and update the code to test the property location
      //var instance = new NexEventApi.EventCreateDto();
      //expect(instance).to.be();
    });

    it('should have the property latitude (base name: "latitude")', function() {
      // uncomment below and update the code to test the property latitude
      //var instance = new NexEventApi.EventCreateDto();
      //expect(instance).to.be();
    });

    it('should have the property longitude (base name: "longitude")', function() {
      // uncomment below and update the code to test the property longitude
      //var instance = new NexEventApi.EventCreateDto();
      //expect(instance).to.be();
    });

    it('should have the property address (base name: "address")', function() {
      // uncomment below and update the code to test the property address
      //var instance = new NexEventApi.EventCreateDto();
      //expect(instance).to.be();
    });

    it('should have the property country (base name: "country")', function() {
      // uncomment below and update the code to test the property country
      //var instance = new NexEventApi.EventCreateDto();
      //expect(instance).to.be();
    });

    it('should have the property city (base name: "city")', function() {
      // uncomment below and update the code to test the property city
      //var instance = new NexEventApi.EventCreateDto();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instance = new NexEventApi.EventCreateDto();
      //expect(instance).to.be();
    });

    it('should have the property complement (base name: "complement")', function() {
      // uncomment below and update the code to test the property complement
      //var instance = new NexEventApi.EventCreateDto();
      //expect(instance).to.be();
    });

    it('should have the property number (base name: "number")', function() {
      // uncomment below and update the code to test the property number
      //var instance = new NexEventApi.EventCreateDto();
      //expect(instance).to.be();
    });

    it('should have the property district (base name: "district")', function() {
      // uncomment below and update the code to test the property district
      //var instance = new NexEventApi.EventCreateDto();
      //expect(instance).to.be();
    });

    it('should have the property sellOnThePlatform (base name: "sellOnThePlatform")', function() {
      // uncomment below and update the code to test the property sellOnThePlatform
      //var instance = new NexEventApi.EventCreateDto();
      //expect(instance).to.be();
    });

    it('should have the property eventSchedule (base name: "eventSchedule")', function() {
      // uncomment below and update the code to test the property eventSchedule
      //var instance = new NexEventApi.EventCreateDto();
      //expect(instance).to.be();
    });

    it('should have the property eventConfig (base name: "eventConfig")', function() {
      // uncomment below and update the code to test the property eventConfig
      //var instance = new NexEventApi.EventCreateDto();
      //expect(instance).to.be();
    });

    it('should have the property eventTickets (base name: "eventTickets")', function() {
      // uncomment below and update the code to test the property eventTickets
      //var instance = new NexEventApi.EventCreateDto();
      //expect(instance).to.be();
    });

  });

}));
