/**
 * Nex Event API
 * Utilize essa documentação para realizar a integração com o nosso sistema
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NexEventApi);
  }
}(this, function(expect, NexEventApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NexEventApi.EventTicketLinkResponseDtoInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EventTicketLinkResponseDtoInner', function() {
    it('should create an instance of EventTicketLinkResponseDtoInner', function() {
      // uncomment below and update the code to test EventTicketLinkResponseDtoInner
      //var instance = new NexEventApi.EventTicketLinkResponseDtoInner();
      //expect(instance).to.be.a(NexEventApi.EventTicketLinkResponseDtoInner);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new NexEventApi.EventTicketLinkResponseDtoInner();
      //expect(instance).to.be();
    });

    it('should have the property eventTicketId (base name: "eventTicketId")', function() {
      // uncomment below and update the code to test the property eventTicketId
      //var instance = new NexEventApi.EventTicketLinkResponseDtoInner();
      //expect(instance).to.be();
    });

    it('should have the property invite (base name: "invite")', function() {
      // uncomment below and update the code to test the property invite
      //var instance = new NexEventApi.EventTicketLinkResponseDtoInner();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new NexEventApi.EventTicketLinkResponseDtoInner();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new NexEventApi.EventTicketLinkResponseDtoInner();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updatedAt")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new NexEventApi.EventTicketLinkResponseDtoInner();
      //expect(instance).to.be();
    });

    it('should have the property participant (base name: "participant")', function() {
      // uncomment below and update the code to test the property participant
      //var instance = new NexEventApi.EventTicketLinkResponseDtoInner();
      //expect(instance).to.be();
    });

  });

}));
