/**
 * Nex Event API
 * Utilize essa documentação para realizar a integração com o nosso sistema
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NexEventApi);
  }
}(this, function(expect, NexEventApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NexEventApi.EventTicketCouponResponseDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EventTicketCouponResponseDto', function() {
    it('should create an instance of EventTicketCouponResponseDto', function() {
      // uncomment below and update the code to test EventTicketCouponResponseDto
      //var instance = new NexEventApi.EventTicketCouponResponseDto();
      //expect(instance).to.be.a(NexEventApi.EventTicketCouponResponseDto);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new NexEventApi.EventTicketCouponResponseDto();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new NexEventApi.EventTicketCouponResponseDto();
      //expect(instance).to.be();
    });

    it('should have the property code (base name: "code")', function() {
      // uncomment below and update the code to test the property code
      //var instance = new NexEventApi.EventTicketCouponResponseDto();
      //expect(instance).to.be();
    });

    it('should have the property percentOff (base name: "percentOff")', function() {
      // uncomment below and update the code to test the property percentOff
      //var instance = new NexEventApi.EventTicketCouponResponseDto();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new NexEventApi.EventTicketCouponResponseDto();
      //expect(instance).to.be();
    });

    it('should have the property expireAt (base name: "expireAt")', function() {
      // uncomment below and update the code to test the property expireAt
      //var instance = new NexEventApi.EventTicketCouponResponseDto();
      //expect(instance).to.be();
    });

    it('should have the property tickets (base name: "tickets")', function() {
      // uncomment below and update the code to test the property tickets
      //var instance = new NexEventApi.EventTicketCouponResponseDto();
      //expect(instance).to.be();
    });

  });

}));
