/**
 * Nex Event API
 * Utilize essa documentação para realizar a integração com o nosso sistema
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NexEventApi);
  }
}(this, function(expect, NexEventApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NexEventApi.FindOneDashboardParticipantPanelDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FindOneDashboardParticipantPanelDto', function() {
    it('should create an instance of FindOneDashboardParticipantPanelDto', function() {
      // uncomment below and update the code to test FindOneDashboardParticipantPanelDto
      //var instance = new NexEventApi.FindOneDashboardParticipantPanelDto();
      //expect(instance).to.be.a(NexEventApi.FindOneDashboardParticipantPanelDto);
    });

    it('should have the property eventLimit (base name: "eventLimit")', function() {
      // uncomment below and update the code to test the property eventLimit
      //var instance = new NexEventApi.FindOneDashboardParticipantPanelDto();
      //expect(instance).to.be();
    });

    it('should have the property eventParticipantsCount (base name: "eventParticipantsCount")', function() {
      // uncomment below and update the code to test the property eventParticipantsCount
      //var instance = new NexEventApi.FindOneDashboardParticipantPanelDto();
      //expect(instance).to.be();
    });

    it('should have the property eventParticipantAwaitPayment (base name: "eventParticipantAwaitPayment")', function() {
      // uncomment below and update the code to test the property eventParticipantAwaitPayment
      //var instance = new NexEventApi.FindOneDashboardParticipantPanelDto();
      //expect(instance).to.be();
    });

    it('should have the property eventEndDate (base name: "eventEndDate")', function() {
      // uncomment below and update the code to test the property eventEndDate
      //var instance = new NexEventApi.FindOneDashboardParticipantPanelDto();
      //expect(instance).to.be();
    });

    it('should have the property eventParcitipantAccreditationsCount (base name: "eventParcitipantAccreditationsCount")', function() {
      // uncomment below and update the code to test the property eventParcitipantAccreditationsCount
      //var instance = new NexEventApi.FindOneDashboardParticipantPanelDto();
      //expect(instance).to.be();
    });

    it('should have the property eventParcitipantAccreditationsPercentual (base name: "eventParcitipantAccreditationsPercentual")', function() {
      // uncomment below and update the code to test the property eventParcitipantAccreditationsPercentual
      //var instance = new NexEventApi.FindOneDashboardParticipantPanelDto();
      //expect(instance).to.be();
    });

    it('should have the property eventParticipantAccreditationsPerMinute (base name: "eventParticipantAccreditationsPerMinute")', function() {
      // uncomment below and update the code to test the property eventParticipantAccreditationsPerMinute
      //var instance = new NexEventApi.FindOneDashboardParticipantPanelDto();
      //expect(instance).to.be();
    });

    it('should have the property eventAverageLocation (base name: "eventAverageLocation")', function() {
      // uncomment below and update the code to test the property eventAverageLocation
      //var instance = new NexEventApi.FindOneDashboardParticipantPanelDto();
      //expect(instance).to.be();
    });

  });

}));
