/**
 * Nex Event API
 * Utilize essa documentação para realizar a integração com o nosso sistema
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NexEventApi);
  }
}(this, function(expect, NexEventApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NexEventApi.EventProducerStaffApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EventProducerStaffApi', function() {
    describe('eventProducerStaffControllerCreateStaff', function() {
      it('should call eventProducerStaffControllerCreateStaff successfully', function(done) {
        //uncomment below and update the code to test eventProducerStaffControllerCreateStaff
        //instance.eventProducerStaffControllerCreateStaff(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('eventProducerStaffControllerDelete', function() {
      it('should call eventProducerStaffControllerDelete successfully', function(done) {
        //uncomment below and update the code to test eventProducerStaffControllerDelete
        //instance.eventProducerStaffControllerDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('eventProducerStaffControllerListEventStaff', function() {
      it('should call eventProducerStaffControllerListEventStaff successfully', function(done) {
        //uncomment below and update the code to test eventProducerStaffControllerListEventStaff
        //instance.eventProducerStaffControllerListEventStaff(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('eventProducerStaffControllerRecommendStaffs', function() {
      it('should call eventProducerStaffControllerRecommendStaffs successfully', function(done) {
        //uncomment below and update the code to test eventProducerStaffControllerRecommendStaffs
        //instance.eventProducerStaffControllerRecommendStaffs(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('eventProducerStaffControllerResendInviteEmail', function() {
      it('should call eventProducerStaffControllerResendInviteEmail successfully', function(done) {
        //uncomment below and update the code to test eventProducerStaffControllerResendInviteEmail
        //instance.eventProducerStaffControllerResendInviteEmail(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('eventProducerStaffControllerStaffEvents', function() {
      it('should call eventProducerStaffControllerStaffEvents successfully', function(done) {
        //uncomment below and update the code to test eventProducerStaffControllerStaffEvents
        //instance.eventProducerStaffControllerStaffEvents(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('eventProducerStaffControllerUpdateEventStaff', function() {
      it('should call eventProducerStaffControllerUpdateEventStaff successfully', function(done) {
        //uncomment below and update the code to test eventProducerStaffControllerUpdateEventStaff
        //instance.eventProducerStaffControllerUpdateEventStaff(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
