/**
 * Nex Event API
 * Utilize essa documentação para realizar a integração com o nosso sistema
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NexEventApi);
  }
}(this, function(expect, NexEventApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NexEventApi.EventQuizApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EventQuizApi', function() {
    describe('eventQuizControllerAlterQuizStatus', function() {
      it('should call eventQuizControllerAlterQuizStatus successfully', function(done) {
        //uncomment below and update the code to test eventQuizControllerAlterQuizStatus
        //instance.eventQuizControllerAlterQuizStatus(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('eventQuizControllerCreateQuiz', function() {
      it('should call eventQuizControllerCreateQuiz successfully', function(done) {
        //uncomment below and update the code to test eventQuizControllerCreateQuiz
        //instance.eventQuizControllerCreateQuiz(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('eventQuizControllerCreateQuizQuestions', function() {
      it('should call eventQuizControllerCreateQuizQuestions successfully', function(done) {
        //uncomment below and update the code to test eventQuizControllerCreateQuizQuestions
        //instance.eventQuizControllerCreateQuizQuestions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('eventQuizControllerFindAllQuizzes', function() {
      it('should call eventQuizControllerFindAllQuizzes successfully', function(done) {
        //uncomment below and update the code to test eventQuizControllerFindAllQuizzes
        //instance.eventQuizControllerFindAllQuizzes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('eventQuizControllerQuizDashboard', function() {
      it('should call eventQuizControllerQuizDashboard successfully', function(done) {
        //uncomment below and update the code to test eventQuizControllerQuizDashboard
        //instance.eventQuizControllerQuizDashboard(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('eventQuizControllerQuizParticipantResponse', function() {
      it('should call eventQuizControllerQuizParticipantResponse successfully', function(done) {
        //uncomment below and update the code to test eventQuizControllerQuizParticipantResponse
        //instance.eventQuizControllerQuizParticipantResponse(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('eventQuizControllerQuizParticipantsResponse', function() {
      it('should call eventQuizControllerQuizParticipantsResponse successfully', function(done) {
        //uncomment below and update the code to test eventQuizControllerQuizParticipantsResponse
        //instance.eventQuizControllerQuizParticipantsResponse(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
